2m_temperature_downloader:
  product_type: reanalysis
  format: netcdf
  variable:
    - 2m_temperature
  year: ["2023", "2024", "2025"]
  month: [ "01", "02", "03", "04", 
          "05", "06", "07", "08", 
          "09", "10", "11", "12" ]
  day:  [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
          "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
          "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
          "31" ]
  time: [ "00:00", "06:00", "12:00", "18:00" ]

wind_speed_downloader:
  product_type: reanalysis
  format: netcdf
  variable:
    - 10m_u_component_of_wind
    - 10m_v_component_of_wind
  year: ["2023", "2024", "2025"]
  month: [ "01", "02", "03", "04", 
          "05", "06", "07", "08", 
          "09", "10", "11", "12" ]
  day:  [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
          "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
          "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
          "31" ]
  time: [ "00:00", "06:00", "12:00", "18:00" ]

surface_pressure_downloader:
  product_type: reanalysis
  format: netcdf
  variable:
    - surface_pressure
  year: ["2023", "2024", "2025"]
  month: [ "01", "02", "03", "04", 
          "05", "06", "07", "08", 
          "09", "10", "11", "12" ]
  day:  [ "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
          "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
          "21", "22", "23", "24", "25", "26", "27", "28", "29", "30",
          "31" ]
  time: [ "00:00", "06:00", "12:00", "18:00" ]